### ISSUE TITLE
boost include files can't be found via Cocoapods 1.0

### ISSUE THREAD

**Issue by dautermann** [tonystone/geofeatures#117]
While building GeoFeatures via Cocoapods 1.0.X, I'm seeing errors that look like this:

```
In file included from /Users/me/Source/climate-iphone/Pods/GeoFeatures/GeoFeatures/GFBox.mm:27:
In file included from /Users/meSource/climate-iphone/Pods/GeoFeatures/GeoFeatures/internal/geofeatures/Box.hpp:30:
/Users/me/Source/climate-iphone/Pods/GeoFeatures/GeoFeatures/internal/geofeatures/Point.hpp:31:10: fatal error: 'boost/mpl/int.hpp' file not found
#include <boost/mpl/int.hpp>
         ^
1 error generated.
```

To get around this, I need to go into the Pods -> GeoFeatures target settings and make two changes: 1) set "Always Search User Paths" to true and 2) add in a path to the Pod/GeoFeatures folder and set it to "recursive". This probably isn't the correct long term solution.

Is there a better solution that can be done?

**Comment by tonystone** [comment]
GeoFeatures 1.6.5 fixes all issues with the latest cocoapods.
